pipeline {
  
   agent{       
     docker{         
       image 'maven:3.6.1-jdk-8-alpine'         
       args '-v $HOME/.m2:/root/.m2'      
     }
    
    }

  
  stages{
      stage('build'){
          steps{
              echo 'Compiling woker app'
              dir('worker'){
                  
                sh 'mvn sompile'
              }
          }
      }
      stage('test'){
          steps{
              echo 'Running Unit Tests on worker app'
          }
      }
      stage('package'){
          steps{
              echo 'Packaging worker app'
          }
      }
  }
  
  post{
      always{
          echo 'Build pipeline for worker is complete...'
      }
  }
