pipeline {
  
  agent any
  
  tools {
        maven 'Maven 3.6.1' 
    }
  
  stages{
      stage('build'){
          steps{
              echo 'Compiling woker app'
              dir('worker'){
                  
                sh 'mvn sompile'
              }
          }
      }
      stage('test'){
          steps{
              echo 'Running Unit Tests on worker app'
          }
      }
      stage('package'){
          steps{
              echo 'Packaging worker app'
          }
      }
  }
  
  post{
      always{
          echo 'Build pipeline for worker is complete...'
      }
  }
